// <auto-generated />
using System;
using LamuFlix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LamuFlix.Data.Migrations
{
    [DbContext(typeof(LamuFlixContext))]
    [Migration("20180917031551_initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LamuFlix.Data.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("actor");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("collection");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("director");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("genre");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CollectionId");

                    b.Property<string>("Duration");

                    b.Property<string>("Format");

                    b.Property<string>("ImdbRating");

                    b.Property<string>("Location");

                    b.Property<string>("Poster");

                    b.Property<string>("Synopsis");

                    b.Property<string>("Title");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Title");

                    b.HasIndex("Year");

                    b.ToTable("movie");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.MovieActors", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("ActorId");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("movieactors");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.MovieDirectors", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("DirectorId");

                    b.HasKey("MovieId", "DirectorId");

                    b.HasIndex("DirectorId");

                    b.ToTable("moviedirectors");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("GenreId");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("moviegenre");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Formats");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("player");

                    b.HasData(
                        new { Id = 1, Formats = ".webm, .xvid, .avi, .mpg, .mp4, .3ivx, .mov, .ogm, .mkv, .asf, .wmv, .dv, .mp4, .flv", Name = "bsplayer", Path = "D:\\Program Files (x86)\\Webteh\\BSPlayer\\bsplayer.exe" },
                        new { Id = 2, Formats = ".rm, .rmvb", Name = "RealPlayer", Path = "D:\\Program Files\\RealPlayer\\realplay.exe" }
                    );
                });

            modelBuilder.Entity("LamuFlix.Data.Models.Movie", b =>
                {
                    b.HasOne("LamuFlix.Data.Models.Collection", "Collection")
                        .WithMany("Movies")
                        .HasForeignKey("CollectionId");
                });

            modelBuilder.Entity("LamuFlix.Data.Models.MovieActors", b =>
                {
                    b.HasOne("LamuFlix.Data.Models.Actor", "Actor")
                        .WithMany("Movies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LamuFlix.Data.Models.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LamuFlix.Data.Models.MovieDirectors", b =>
                {
                    b.HasOne("LamuFlix.Data.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LamuFlix.Data.Models.Movie", "Movie")
                        .WithMany("Directors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LamuFlix.Data.Models.MovieGenre", b =>
                {
                    b.HasOne("LamuFlix.Data.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LamuFlix.Data.Models.Movie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
