<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <UserSecretsId>d36feb09-3e70-4fa7-b925-cd92c46cf9fd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\images\lamuflix-LOGO.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LamuFlix.Data\LamuFlix.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>LamuFlix.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="img\" />
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
