// <auto-generated />
using System;
using LamuFlix.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LamuFlix.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LamuFlixDbContext))]
    partial class LamuFlixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LamuFlix.Infrastructure.Persistence.Records.ActorRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("LamuFlix.Infrastructure.Persistence.Records.DirectorRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("directors", (string)null);
                });

            modelBuilder.Entity("LamuFlix.Infrastructure.Persistence.Records.GenreRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("LamuFlix.Infrastructure.Persistence.Records.MovieRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EnrichedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("enriched_at");

                    b.Property<int>("EnrichmentAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("enrichment_attempts");

                    b.Property<string>("EnrichmentFailureCategory")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("enrichment_failure_category");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<decimal?>("ImdbRating")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("imdb_rating");

                    b.Property<bool>("IsInWatchlist")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_watchlist");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("library_path");

                    b.Property<short?>("MetaScore")
                        .HasColumnType("smallint")
                        .HasColumnName("meta_score");

                    b.Property<string>("MetadataTitle")
                        .HasColumnType("text")
                        .HasColumnName("metadata_title");

                    b.Property<string>("Plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<short?>("RottenTomatoesRating")
                        .HasColumnType("smallint")
                        .HasColumnName("rotten_tomatoes_rating");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId")
                        .IsUnique()
                        .HasFilter("imdb_id IS NOT NULL");

                    b.HasIndex("LibraryPath")
                        .IsUnique();

                    b.HasIndex("ReleaseYear");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("movie_actors", b =>
                {
                    b.Property<int>("actor_id")
                        .HasColumnType("integer");

                    b.Property<int>("movie_id")
                        .HasColumnType("integer");

                    b.HasKey("actor_id", "movie_id");

                    b.HasIndex("movie_id");

                    b.ToTable("movie_actors");
                });

            modelBuilder.Entity("movie_directors", b =>
                {
                    b.Property<int>("director_id")
                        .HasColumnType("integer");

                    b.Property<int>("movie_id")
                        .HasColumnType("integer");

                    b.HasKey("director_id", "movie_id");

                    b.HasIndex("movie_id");

                    b.ToTable("movie_directors");
                });

            modelBuilder.Entity("movie_genres", b =>
                {
                    b.Property<int>("genre_id")
                        .HasColumnType("integer");

                    b.Property<int>("movie_id")
                        .HasColumnType("integer");

                    b.HasKey("genre_id", "movie_id");

                    b.HasIndex("movie_id");

                    b.ToTable("movie_genres");
                });

            modelBuilder.Entity("movie_actors", b =>
                {
                    b.HasOne("LamuFlix.Infrastructure.Persistence.Records.ActorRecord", null)
                        .WithMany()
                        .HasForeignKey("actor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LamuFlix.Infrastructure.Persistence.Records.MovieRecord", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_directors", b =>
                {
                    b.HasOne("LamuFlix.Infrastructure.Persistence.Records.DirectorRecord", null)
                        .WithMany()
                        .HasForeignKey("director_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LamuFlix.Infrastructure.Persistence.Records.MovieRecord", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_genres", b =>
                {
                    b.HasOne("LamuFlix.Infrastructure.Persistence.Records.GenreRecord", null)
                        .WithMany()
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LamuFlix.Infrastructure.Persistence.Records.MovieRecord", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
