<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Moq" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LamuFlix.Data\LamuFlix.Data.csproj" />
    <ProjectReference Include="..\..\src\LamuFlix.Web\LamuFlix.Web.csproj" />
    <ProjectReference Include="..\..\src\LamuFlix.Worker\LamuFlix.Worker.csproj" />
  </ItemGroup>

</Project>
